root: true
env:
  browser: true
  es2021: true
  'jest/globals': true
extends:
  - standard
  - prettier
parser: '@typescript-eslint/parser'
plugins:
  - jest
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  NodeJS: true
rules: {}
